version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/cache:/data-cache
    environment:
      - TZ=Asia/Bangkok
      - NGINX_PORT=80
    restart: always
    networks:
      - frontend-network
  web01:
    image: codesmashteam/phpcodesmash:latest
    volumes:
      - ./docroot:/var/www/html
    environment:
      - TZ=Asia/Bangkok
    networks: -frontend-network
      -backend-network
    hostname: web
    restart: always
  mysql:
    image: mysql:8.0.22
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connection='SET NAMES UTF8' --innodb-flush-log-at-trx-commit=0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    restart: always
    ports:
      - "3306:3306"
    networks: -backend-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    restart: always
    networks: -backend-network

networks:
  frontend-network:
  backend-network:
